{
 "title": "Bomberman",
 "time": { "from": "2021-04-03T08:11:48.468Z", "to": "2021-04-03T08:26:14.728Z" },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Frame Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(xyz_bomberman_frames_total[1m])"
    },
    {}
   ]
  },
  {
   "title": "Cancel Frame Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(xyz_bomberman_frames_total{frame=\"CANCEL\"}[1m])"
    }
   ]
  },
  {
   "title": "Error Frame Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(xyz_bomberman_frames_total{frame=\"ERROR\"}[1m])  "
    }
   ]
  },
  {
   "title": "Max Req/Res latency (ms)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "xyz_bomberman_reqres_timer_seconds_max * 1000"
    }
   ]
  }
 ]
}