// automatically generated by the FlatBuffers compiler, do not modify

/**
 * @const
 * @namespace
 */
var xyz = xyz || {};

/**
 * @const
 * @namespace
 */
xyz.bomberman = xyz.bomberman || {};

/**
 * @const
 * @namespace
 */
xyz.bomberman.game = xyz.bomberman.game || {};

/**
 * @const
 * @namespace
 */
xyz.bomberman.game.data = xyz.bomberman.game.data || {};

/**
 * @constructor
 */
xyz.bomberman.game.data.Position = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {xyz.bomberman.game.data.Position}
 */
xyz.bomberman.game.data.Position.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @returns {number}
 */
xyz.bomberman.game.data.Position.prototype.x = function() {
  return this.bb.readInt32(this.bb_pos);
};

/**
 * @param {number} value
 * @returns {boolean}
 */
xyz.bomberman.game.data.Position.prototype.mutate_x = function(value) {
  var offset = this.bb.__offset(this.bb_pos, 0);

  if (offset === 0) {
    return false;
  }

  this.bb.writeInt32(this.bb_pos + offset, value);
  return true;
};

/**
 * @returns {number}
 */
xyz.bomberman.game.data.Position.prototype.y = function() {
  return this.bb.readInt32(this.bb_pos + 4);
};

/**
 * @param {number} value
 * @returns {boolean}
 */
xyz.bomberman.game.data.Position.prototype.mutate_y = function(value) {
  var offset = this.bb.__offset(this.bb_pos, 4);

  if (offset === 0) {
    return false;
  }

  this.bb.writeInt32(this.bb_pos + offset, value);
  return true;
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} x
 * @param {number} y
 * @returns {flatbuffers.Offset}
 */
xyz.bomberman.game.data.Position.createPosition = function(builder, x, y) {
  builder.prep(4, 8);
  builder.writeInt32(y);
  builder.writeInt32(x);
  return builder.offset();
};

/**
 * @constructor
 */
xyz.bomberman.game.data.Item = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {xyz.bomberman.game.data.Item}
 */
xyz.bomberman.game.data.Item.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {xyz.bomberman.game.data.Item=} obj
 * @returns {xyz.bomberman.game.data.Item}
 */
xyz.bomberman.game.data.Item.getRootAsItem = function(bb, obj) {
  return (obj || new xyz.bomberman.game.data.Item).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {xyz.bomberman.game.data.Item=} obj
 * @returns {xyz.bomberman.game.data.Item}
 */
xyz.bomberman.game.data.Item.getSizePrefixedRootAsItem = function(bb, obj) {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new xyz.bomberman.game.data.Item).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {xyz.bomberman.game.data.Position=} obj
 * @returns {xyz.bomberman.game.data.Position|null}
 */
xyz.bomberman.game.data.Item.prototype.position = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? (obj || new xyz.bomberman.game.data.Position).__init(this.bb_pos + offset, this.bb) : null;
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
xyz.bomberman.game.data.Item.prototype.type = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
xyz.bomberman.game.data.Item.startItem = function(builder) {
  builder.startObject(2);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} positionOffset
 */
xyz.bomberman.game.data.Item.addPosition = function(builder, positionOffset) {
  builder.addFieldStruct(0, positionOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} typeOffset
 */
xyz.bomberman.game.data.Item.addType = function(builder, typeOffset) {
  builder.addFieldOffset(1, typeOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
xyz.bomberman.game.data.Item.endItem = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} positionOffset
 * @param {flatbuffers.Offset} typeOffset
 * @returns {flatbuffers.Offset}
 */
xyz.bomberman.game.data.Item.createItem = function(builder, positionOffset, typeOffset) {
  xyz.bomberman.game.data.Item.startItem(builder);
  xyz.bomberman.game.data.Item.addPosition(builder, positionOffset);
  xyz.bomberman.game.data.Item.addType(builder, typeOffset);
  return xyz.bomberman.game.data.Item.endItem(builder);
}

/**
 * @constructor
 */
xyz.bomberman.game.data.Wall = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {xyz.bomberman.game.data.Wall}
 */
xyz.bomberman.game.data.Wall.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {xyz.bomberman.game.data.Wall=} obj
 * @returns {xyz.bomberman.game.data.Wall}
 */
xyz.bomberman.game.data.Wall.getRootAsWall = function(bb, obj) {
  return (obj || new xyz.bomberman.game.data.Wall).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {xyz.bomberman.game.data.Wall=} obj
 * @returns {xyz.bomberman.game.data.Wall}
 */
xyz.bomberman.game.data.Wall.getSizePrefixedRootAsWall = function(bb, obj) {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new xyz.bomberman.game.data.Wall).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
xyz.bomberman.game.data.Wall.prototype.id = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {xyz.bomberman.game.data.Position=} obj
 * @returns {xyz.bomberman.game.data.Position|null}
 */
xyz.bomberman.game.data.Wall.prototype.position = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? (obj || new xyz.bomberman.game.data.Position).__init(this.bb_pos + offset, this.bb) : null;
};

/**
 * @returns {boolean}
 */
xyz.bomberman.game.data.Wall.prototype.isDestructible = function() {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? !!this.bb.readInt8(this.bb_pos + offset) : false;
};

/**
 * @param {boolean} value
 * @returns {boolean}
 */
xyz.bomberman.game.data.Wall.prototype.mutate_isDestructible = function(value) {
  var offset = this.bb.__offset(this.bb_pos, 8);

  if (offset === 0) {
    return false;
  }

  this.bb.writeInt8(this.bb_pos + offset, value);
  return true;
};

/**
 * @param {flatbuffers.Builder} builder
 */
xyz.bomberman.game.data.Wall.startWall = function(builder) {
  builder.startObject(3);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} idOffset
 */
xyz.bomberman.game.data.Wall.addId = function(builder, idOffset) {
  builder.addFieldOffset(0, idOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} positionOffset
 */
xyz.bomberman.game.data.Wall.addPosition = function(builder, positionOffset) {
  builder.addFieldStruct(1, positionOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {boolean} isDestructible
 */
xyz.bomberman.game.data.Wall.addIsDestructible = function(builder, isDestructible) {
  builder.addFieldInt8(2, +isDestructible, +false);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
xyz.bomberman.game.data.Wall.endWall = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} idOffset
 * @param {flatbuffers.Offset} positionOffset
 * @param {boolean} isDestructible
 * @returns {flatbuffers.Offset}
 */
xyz.bomberman.game.data.Wall.createWall = function(builder, idOffset, positionOffset, isDestructible) {
  xyz.bomberman.game.data.Wall.startWall(builder);
  xyz.bomberman.game.data.Wall.addId(builder, idOffset);
  xyz.bomberman.game.data.Wall.addPosition(builder, positionOffset);
  xyz.bomberman.game.data.Wall.addIsDestructible(builder, isDestructible);
  return xyz.bomberman.game.data.Wall.endWall(builder);
}

/**
 * @constructor
 */
xyz.bomberman.game.data.Player = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {xyz.bomberman.game.data.Player}
 */
xyz.bomberman.game.data.Player.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {xyz.bomberman.game.data.Player=} obj
 * @returns {xyz.bomberman.game.data.Player}
 */
xyz.bomberman.game.data.Player.getRootAsPlayer = function(bb, obj) {
  return (obj || new xyz.bomberman.game.data.Player).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {xyz.bomberman.game.data.Player=} obj
 * @returns {xyz.bomberman.game.data.Player}
 */
xyz.bomberman.game.data.Player.getSizePrefixedRootAsPlayer = function(bb, obj) {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new xyz.bomberman.game.data.Player).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
xyz.bomberman.game.data.Player.prototype.id = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {xyz.bomberman.game.data.Position=} obj
 * @returns {xyz.bomberman.game.data.Position|null}
 */
xyz.bomberman.game.data.Player.prototype.position = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? (obj || new xyz.bomberman.game.data.Position).__init(this.bb_pos + offset, this.bb) : null;
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
xyz.bomberman.game.data.Player.prototype.direction = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @returns {number}
 */
xyz.bomberman.game.data.Player.prototype.amountBombs = function() {
  var offset = this.bb.__offset(this.bb_pos, 10);
  return offset ? this.bb.readInt32(this.bb_pos + offset) : 0;
};

/**
 * @param {number} value
 * @returns {boolean}
 */
xyz.bomberman.game.data.Player.prototype.mutate_amountBombs = function(value) {
  var offset = this.bb.__offset(this.bb_pos, 10);

  if (offset === 0) {
    return false;
  }

  this.bb.writeInt32(this.bb_pos + offset, value);
  return true;
};

/**
 * @returns {number}
 */
xyz.bomberman.game.data.Player.prototype.amountWalls = function() {
  var offset = this.bb.__offset(this.bb_pos, 12);
  return offset ? this.bb.readInt32(this.bb_pos + offset) : 0;
};

/**
 * @param {number} value
 * @returns {boolean}
 */
xyz.bomberman.game.data.Player.prototype.mutate_amountWalls = function(value) {
  var offset = this.bb.__offset(this.bb_pos, 12);

  if (offset === 0) {
    return false;
  }

  this.bb.writeInt32(this.bb_pos + offset, value);
  return true;
};

/**
 * @returns {number}
 */
xyz.bomberman.game.data.Player.prototype.health = function() {
  var offset = this.bb.__offset(this.bb_pos, 14);
  return offset ? this.bb.readInt32(this.bb_pos + offset) : 0;
};

/**
 * @param {number} value
 * @returns {boolean}
 */
xyz.bomberman.game.data.Player.prototype.mutate_health = function(value) {
  var offset = this.bb.__offset(this.bb_pos, 14);

  if (offset === 0) {
    return false;
  }

  this.bb.writeInt32(this.bb_pos + offset, value);
  return true;
};

/**
 * @param {flatbuffers.Builder} builder
 */
xyz.bomberman.game.data.Player.startPlayer = function(builder) {
  builder.startObject(6);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} idOffset
 */
xyz.bomberman.game.data.Player.addId = function(builder, idOffset) {
  builder.addFieldOffset(0, idOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} positionOffset
 */
xyz.bomberman.game.data.Player.addPosition = function(builder, positionOffset) {
  builder.addFieldStruct(1, positionOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} directionOffset
 */
xyz.bomberman.game.data.Player.addDirection = function(builder, directionOffset) {
  builder.addFieldOffset(2, directionOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} amountBombs
 */
xyz.bomberman.game.data.Player.addAmountBombs = function(builder, amountBombs) {
  builder.addFieldInt32(3, amountBombs, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} amountWalls
 */
xyz.bomberman.game.data.Player.addAmountWalls = function(builder, amountWalls) {
  builder.addFieldInt32(4, amountWalls, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} health
 */
xyz.bomberman.game.data.Player.addHealth = function(builder, health) {
  builder.addFieldInt32(5, health, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
xyz.bomberman.game.data.Player.endPlayer = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} idOffset
 * @param {flatbuffers.Offset} positionOffset
 * @param {flatbuffers.Offset} directionOffset
 * @param {number} amountBombs
 * @param {number} amountWalls
 * @param {number} health
 * @returns {flatbuffers.Offset}
 */
xyz.bomberman.game.data.Player.createPlayer = function(builder, idOffset, positionOffset, directionOffset, amountBombs, amountWalls, health) {
  xyz.bomberman.game.data.Player.startPlayer(builder);
  xyz.bomberman.game.data.Player.addId(builder, idOffset);
  xyz.bomberman.game.data.Player.addPosition(builder, positionOffset);
  xyz.bomberman.game.data.Player.addDirection(builder, directionOffset);
  xyz.bomberman.game.data.Player.addAmountBombs(builder, amountBombs);
  xyz.bomberman.game.data.Player.addAmountWalls(builder, amountWalls);
  xyz.bomberman.game.data.Player.addHealth(builder, health);
  return xyz.bomberman.game.data.Player.endPlayer(builder);
}

/**
 * @constructor
 */
xyz.bomberman.game.data.Game = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {xyz.bomberman.game.data.Game}
 */
xyz.bomberman.game.data.Game.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {xyz.bomberman.game.data.Game=} obj
 * @returns {xyz.bomberman.game.data.Game}
 */
xyz.bomberman.game.data.Game.getRootAsGame = function(bb, obj) {
  return (obj || new xyz.bomberman.game.data.Game).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {xyz.bomberman.game.data.Game=} obj
 * @returns {xyz.bomberman.game.data.Game}
 */
xyz.bomberman.game.data.Game.getSizePrefixedRootAsGame = function(bb, obj) {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new xyz.bomberman.game.data.Game).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {number} index
 * @param {xyz.bomberman.game.data.Player=} obj
 * @returns {xyz.bomberman.game.data.Player}
 */
xyz.bomberman.game.data.Game.prototype.players = function(index, obj) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? (obj || new xyz.bomberman.game.data.Player).__init(this.bb.__indirect(this.bb.__vector(this.bb_pos + offset) + index * 4), this.bb) : null;
};

/**
 * @returns {number}
 */
xyz.bomberman.game.data.Game.prototype.playersLength = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @param {number} index
 * @param {xyz.bomberman.game.data.Item=} obj
 * @returns {xyz.bomberman.game.data.Item}
 */
xyz.bomberman.game.data.Game.prototype.items = function(index, obj) {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? (obj || new xyz.bomberman.game.data.Item).__init(this.bb.__indirect(this.bb.__vector(this.bb_pos + offset) + index * 4), this.bb) : null;
};

/**
 * @returns {number}
 */
xyz.bomberman.game.data.Game.prototype.itemsLength = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @param {number} index
 * @param {xyz.bomberman.game.data.Wall=} obj
 * @returns {xyz.bomberman.game.data.Wall}
 */
xyz.bomberman.game.data.Game.prototype.walls = function(index, obj) {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? (obj || new xyz.bomberman.game.data.Wall).__init(this.bb.__indirect(this.bb.__vector(this.bb_pos + offset) + index * 4), this.bb) : null;
};

/**
 * @returns {number}
 */
xyz.bomberman.game.data.Game.prototype.wallsLength = function() {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @param {flatbuffers.Builder} builder
 */
xyz.bomberman.game.data.Game.startGame = function(builder) {
  builder.startObject(3);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} playersOffset
 */
xyz.bomberman.game.data.Game.addPlayers = function(builder, playersOffset) {
  builder.addFieldOffset(0, playersOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {Array.<flatbuffers.Offset>} data
 * @returns {flatbuffers.Offset}
 */
xyz.bomberman.game.data.Game.createPlayersVector = function(builder, data) {
  builder.startVector(4, data.length, 4);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]);
  }
  return builder.endVector();
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
xyz.bomberman.game.data.Game.startPlayersVector = function(builder, numElems) {
  builder.startVector(4, numElems, 4);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} itemsOffset
 */
xyz.bomberman.game.data.Game.addItems = function(builder, itemsOffset) {
  builder.addFieldOffset(1, itemsOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {Array.<flatbuffers.Offset>} data
 * @returns {flatbuffers.Offset}
 */
xyz.bomberman.game.data.Game.createItemsVector = function(builder, data) {
  builder.startVector(4, data.length, 4);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]);
  }
  return builder.endVector();
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
xyz.bomberman.game.data.Game.startItemsVector = function(builder, numElems) {
  builder.startVector(4, numElems, 4);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} wallsOffset
 */
xyz.bomberman.game.data.Game.addWalls = function(builder, wallsOffset) {
  builder.addFieldOffset(2, wallsOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {Array.<flatbuffers.Offset>} data
 * @returns {flatbuffers.Offset}
 */
xyz.bomberman.game.data.Game.createWallsVector = function(builder, data) {
  builder.startVector(4, data.length, 4);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]);
  }
  return builder.endVector();
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
xyz.bomberman.game.data.Game.startWallsVector = function(builder, numElems) {
  builder.startVector(4, numElems, 4);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
xyz.bomberman.game.data.Game.endGame = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} offset
 */
xyz.bomberman.game.data.Game.finishGameBuffer = function(builder, offset) {
  builder.finish(offset);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} offset
 */
xyz.bomberman.game.data.Game.finishSizePrefixedGameBuffer = function(builder, offset) {
  builder.finish(offset, undefined, true);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} playersOffset
 * @param {flatbuffers.Offset} itemsOffset
 * @param {flatbuffers.Offset} wallsOffset
 * @returns {flatbuffers.Offset}
 */
xyz.bomberman.game.data.Game.createGame = function(builder, playersOffset, itemsOffset, wallsOffset) {
  xyz.bomberman.game.data.Game.startGame(builder);
  xyz.bomberman.game.data.Game.addPlayers(builder, playersOffset);
  xyz.bomberman.game.data.Game.addItems(builder, itemsOffset);
  xyz.bomberman.game.data.Game.addWalls(builder, wallsOffset);
  return xyz.bomberman.game.data.Game.endGame(builder);
}

// Exports for ECMAScript6 Modules
export {xyz};
