// automatically generated by the FlatBuffers compiler, do not modify

/**
 * @const
 * @namespace
 */
var xyz = xyz || {};

/**
 * @const
 * @namespace
 */
xyz.bomberman = xyz.bomberman || {};

/**
 * @const
 * @namespace
 */
xyz.bomberman.game = xyz.bomberman.game || {};

/**
 * @const
 * @namespace
 */
xyz.bomberman.game.data = xyz.bomberman.game.data || {};

/**
 * @enum {number}
 */
xyz.bomberman.game.data.EventType = {
  NONE: 0,
  Reaction: 1,
  ChangeDirection: 2,
  CreateItem: 3,
  GrabItem: 4,
  HurtPlayer: 5,
  MovePlayer: 6,
  DeletePlayer: 7,
  PlaceBomb: 8,
  UpdateInventory: 9,
  PlaceWall: 10
};

/**
 * @enum {string}
 */
xyz.bomberman.game.data.EventTypeName = {
  '0': 'NONE',
  '1': 'Reaction',
  '2': 'ChangeDirection',
  '3': 'CreateItem',
  '4': 'GrabItem',
  '5': 'HurtPlayer',
  '6': 'MovePlayer',
  '7': 'DeletePlayer',
  '8': 'PlaceBomb',
  '9': 'UpdateInventory',
  '10': 'PlaceWall'
};

/**
 * @constructor
 */
xyz.bomberman.game.data.Position = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {xyz.bomberman.game.data.Position}
 */
xyz.bomberman.game.data.Position.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @returns {number}
 */
xyz.bomberman.game.data.Position.prototype.x = function() {
  return this.bb.readInt32(this.bb_pos);
};

/**
 * @param {number} value
 * @returns {boolean}
 */
xyz.bomberman.game.data.Position.prototype.mutate_x = function(value) {
  var offset = this.bb.__offset(this.bb_pos, 0);

  if (offset === 0) {
    return false;
  }

  this.bb.writeInt32(this.bb_pos + offset, value);
  return true;
};

/**
 * @returns {number}
 */
xyz.bomberman.game.data.Position.prototype.y = function() {
  return this.bb.readInt32(this.bb_pos + 4);
};

/**
 * @param {number} value
 * @returns {boolean}
 */
xyz.bomberman.game.data.Position.prototype.mutate_y = function(value) {
  var offset = this.bb.__offset(this.bb_pos, 4);

  if (offset === 0) {
    return false;
  }

  this.bb.writeInt32(this.bb_pos + offset, value);
  return true;
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} x
 * @param {number} y
 * @returns {flatbuffers.Offset}
 */
xyz.bomberman.game.data.Position.createPosition = function(builder, x, y) {
  builder.prep(4, 8);
  builder.writeInt32(y);
  builder.writeInt32(x);
  return builder.offset();
};

/**
 * @constructor
 */
xyz.bomberman.game.data.Item = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {xyz.bomberman.game.data.Item}
 */
xyz.bomberman.game.data.Item.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {xyz.bomberman.game.data.Item=} obj
 * @returns {xyz.bomberman.game.data.Item}
 */
xyz.bomberman.game.data.Item.getRootAsItem = function(bb, obj) {
  return (obj || new xyz.bomberman.game.data.Item).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {xyz.bomberman.game.data.Item=} obj
 * @returns {xyz.bomberman.game.data.Item}
 */
xyz.bomberman.game.data.Item.getSizePrefixedRootAsItem = function(bb, obj) {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new xyz.bomberman.game.data.Item).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {xyz.bomberman.game.data.Position=} obj
 * @returns {xyz.bomberman.game.data.Position|null}
 */
xyz.bomberman.game.data.Item.prototype.position = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? (obj || new xyz.bomberman.game.data.Position).__init(this.bb_pos + offset, this.bb) : null;
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
xyz.bomberman.game.data.Item.prototype.type = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
xyz.bomberman.game.data.Item.startItem = function(builder) {
  builder.startObject(2);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} positionOffset
 */
xyz.bomberman.game.data.Item.addPosition = function(builder, positionOffset) {
  builder.addFieldStruct(0, positionOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} typeOffset
 */
xyz.bomberman.game.data.Item.addType = function(builder, typeOffset) {
  builder.addFieldOffset(1, typeOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
xyz.bomberman.game.data.Item.endItem = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} positionOffset
 * @param {flatbuffers.Offset} typeOffset
 * @returns {flatbuffers.Offset}
 */
xyz.bomberman.game.data.Item.createItem = function(builder, positionOffset, typeOffset) {
  xyz.bomberman.game.data.Item.startItem(builder);
  xyz.bomberman.game.data.Item.addPosition(builder, positionOffset);
  xyz.bomberman.game.data.Item.addType(builder, typeOffset);
  return xyz.bomberman.game.data.Item.endItem(builder);
}

/**
 * @constructor
 */
xyz.bomberman.game.data.Wall = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {xyz.bomberman.game.data.Wall}
 */
xyz.bomberman.game.data.Wall.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {xyz.bomberman.game.data.Wall=} obj
 * @returns {xyz.bomberman.game.data.Wall}
 */
xyz.bomberman.game.data.Wall.getRootAsWall = function(bb, obj) {
  return (obj || new xyz.bomberman.game.data.Wall).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {xyz.bomberman.game.data.Wall=} obj
 * @returns {xyz.bomberman.game.data.Wall}
 */
xyz.bomberman.game.data.Wall.getSizePrefixedRootAsWall = function(bb, obj) {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new xyz.bomberman.game.data.Wall).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
xyz.bomberman.game.data.Wall.prototype.id = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {xyz.bomberman.game.data.Position=} obj
 * @returns {xyz.bomberman.game.data.Position|null}
 */
xyz.bomberman.game.data.Wall.prototype.position = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? (obj || new xyz.bomberman.game.data.Position).__init(this.bb_pos + offset, this.bb) : null;
};

/**
 * @returns {boolean}
 */
xyz.bomberman.game.data.Wall.prototype.isDestructible = function() {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? !!this.bb.readInt8(this.bb_pos + offset) : false;
};

/**
 * @param {boolean} value
 * @returns {boolean}
 */
xyz.bomberman.game.data.Wall.prototype.mutate_isDestructible = function(value) {
  var offset = this.bb.__offset(this.bb_pos, 8);

  if (offset === 0) {
    return false;
  }

  this.bb.writeInt8(this.bb_pos + offset, value);
  return true;
};

/**
 * @param {flatbuffers.Builder} builder
 */
xyz.bomberman.game.data.Wall.startWall = function(builder) {
  builder.startObject(3);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} idOffset
 */
xyz.bomberman.game.data.Wall.addId = function(builder, idOffset) {
  builder.addFieldOffset(0, idOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} positionOffset
 */
xyz.bomberman.game.data.Wall.addPosition = function(builder, positionOffset) {
  builder.addFieldStruct(1, positionOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {boolean} isDestructible
 */
xyz.bomberman.game.data.Wall.addIsDestructible = function(builder, isDestructible) {
  builder.addFieldInt8(2, +isDestructible, +false);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
xyz.bomberman.game.data.Wall.endWall = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} idOffset
 * @param {flatbuffers.Offset} positionOffset
 * @param {boolean} isDestructible
 * @returns {flatbuffers.Offset}
 */
xyz.bomberman.game.data.Wall.createWall = function(builder, idOffset, positionOffset, isDestructible) {
  xyz.bomberman.game.data.Wall.startWall(builder);
  xyz.bomberman.game.data.Wall.addId(builder, idOffset);
  xyz.bomberman.game.data.Wall.addPosition(builder, positionOffset);
  xyz.bomberman.game.data.Wall.addIsDestructible(builder, isDestructible);
  return xyz.bomberman.game.data.Wall.endWall(builder);
}

/**
 * @constructor
 */
xyz.bomberman.game.data.Player = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {xyz.bomberman.game.data.Player}
 */
xyz.bomberman.game.data.Player.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {xyz.bomberman.game.data.Player=} obj
 * @returns {xyz.bomberman.game.data.Player}
 */
xyz.bomberman.game.data.Player.getRootAsPlayer = function(bb, obj) {
  return (obj || new xyz.bomberman.game.data.Player).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {xyz.bomberman.game.data.Player=} obj
 * @returns {xyz.bomberman.game.data.Player}
 */
xyz.bomberman.game.data.Player.getSizePrefixedRootAsPlayer = function(bb, obj) {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new xyz.bomberman.game.data.Player).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
xyz.bomberman.game.data.Player.prototype.id = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {xyz.bomberman.game.data.Position=} obj
 * @returns {xyz.bomberman.game.data.Position|null}
 */
xyz.bomberman.game.data.Player.prototype.position = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? (obj || new xyz.bomberman.game.data.Position).__init(this.bb_pos + offset, this.bb) : null;
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
xyz.bomberman.game.data.Player.prototype.direction = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @returns {number}
 */
xyz.bomberman.game.data.Player.prototype.amountBombs = function() {
  var offset = this.bb.__offset(this.bb_pos, 10);
  return offset ? this.bb.readInt32(this.bb_pos + offset) : 0;
};

/**
 * @param {number} value
 * @returns {boolean}
 */
xyz.bomberman.game.data.Player.prototype.mutate_amountBombs = function(value) {
  var offset = this.bb.__offset(this.bb_pos, 10);

  if (offset === 0) {
    return false;
  }

  this.bb.writeInt32(this.bb_pos + offset, value);
  return true;
};

/**
 * @returns {number}
 */
xyz.bomberman.game.data.Player.prototype.amountWalls = function() {
  var offset = this.bb.__offset(this.bb_pos, 12);
  return offset ? this.bb.readInt32(this.bb_pos + offset) : 0;
};

/**
 * @param {number} value
 * @returns {boolean}
 */
xyz.bomberman.game.data.Player.prototype.mutate_amountWalls = function(value) {
  var offset = this.bb.__offset(this.bb_pos, 12);

  if (offset === 0) {
    return false;
  }

  this.bb.writeInt32(this.bb_pos + offset, value);
  return true;
};

/**
 * @returns {number}
 */
xyz.bomberman.game.data.Player.prototype.health = function() {
  var offset = this.bb.__offset(this.bb_pos, 14);
  return offset ? this.bb.readInt32(this.bb_pos + offset) : 0;
};

/**
 * @param {number} value
 * @returns {boolean}
 */
xyz.bomberman.game.data.Player.prototype.mutate_health = function(value) {
  var offset = this.bb.__offset(this.bb_pos, 14);

  if (offset === 0) {
    return false;
  }

  this.bb.writeInt32(this.bb_pos + offset, value);
  return true;
};

/**
 * @param {flatbuffers.Builder} builder
 */
xyz.bomberman.game.data.Player.startPlayer = function(builder) {
  builder.startObject(6);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} idOffset
 */
xyz.bomberman.game.data.Player.addId = function(builder, idOffset) {
  builder.addFieldOffset(0, idOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} positionOffset
 */
xyz.bomberman.game.data.Player.addPosition = function(builder, positionOffset) {
  builder.addFieldStruct(1, positionOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} directionOffset
 */
xyz.bomberman.game.data.Player.addDirection = function(builder, directionOffset) {
  builder.addFieldOffset(2, directionOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} amountBombs
 */
xyz.bomberman.game.data.Player.addAmountBombs = function(builder, amountBombs) {
  builder.addFieldInt32(3, amountBombs, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} amountWalls
 */
xyz.bomberman.game.data.Player.addAmountWalls = function(builder, amountWalls) {
  builder.addFieldInt32(4, amountWalls, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} health
 */
xyz.bomberman.game.data.Player.addHealth = function(builder, health) {
  builder.addFieldInt32(5, health, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
xyz.bomberman.game.data.Player.endPlayer = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} idOffset
 * @param {flatbuffers.Offset} positionOffset
 * @param {flatbuffers.Offset} directionOffset
 * @param {number} amountBombs
 * @param {number} amountWalls
 * @param {number} health
 * @returns {flatbuffers.Offset}
 */
xyz.bomberman.game.data.Player.createPlayer = function(builder, idOffset, positionOffset, directionOffset, amountBombs, amountWalls, health) {
  xyz.bomberman.game.data.Player.startPlayer(builder);
  xyz.bomberman.game.data.Player.addId(builder, idOffset);
  xyz.bomberman.game.data.Player.addPosition(builder, positionOffset);
  xyz.bomberman.game.data.Player.addDirection(builder, directionOffset);
  xyz.bomberman.game.data.Player.addAmountBombs(builder, amountBombs);
  xyz.bomberman.game.data.Player.addAmountWalls(builder, amountWalls);
  xyz.bomberman.game.data.Player.addHealth(builder, health);
  return xyz.bomberman.game.data.Player.endPlayer(builder);
}

/**
 * @constructor
 */
xyz.bomberman.game.data.LoginPlayerEvent = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {xyz.bomberman.game.data.LoginPlayerEvent}
 */
xyz.bomberman.game.data.LoginPlayerEvent.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {xyz.bomberman.game.data.LoginPlayerEvent=} obj
 * @returns {xyz.bomberman.game.data.LoginPlayerEvent}
 */
xyz.bomberman.game.data.LoginPlayerEvent.getRootAsLoginPlayerEvent = function(bb, obj) {
  return (obj || new xyz.bomberman.game.data.LoginPlayerEvent).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {xyz.bomberman.game.data.LoginPlayerEvent=} obj
 * @returns {xyz.bomberman.game.data.LoginPlayerEvent}
 */
xyz.bomberman.game.data.LoginPlayerEvent.getSizePrefixedRootAsLoginPlayerEvent = function(bb, obj) {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new xyz.bomberman.game.data.LoginPlayerEvent).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
xyz.bomberman.game.data.LoginPlayerEvent.prototype.id = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
xyz.bomberman.game.data.LoginPlayerEvent.prototype.gameId = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
xyz.bomberman.game.data.LoginPlayerEvent.startLoginPlayerEvent = function(builder) {
  builder.startObject(2);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} idOffset
 */
xyz.bomberman.game.data.LoginPlayerEvent.addId = function(builder, idOffset) {
  builder.addFieldOffset(0, idOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} gameIdOffset
 */
xyz.bomberman.game.data.LoginPlayerEvent.addGameId = function(builder, gameIdOffset) {
  builder.addFieldOffset(1, gameIdOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
xyz.bomberman.game.data.LoginPlayerEvent.endLoginPlayerEvent = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} idOffset
 * @param {flatbuffers.Offset} gameIdOffset
 * @returns {flatbuffers.Offset}
 */
xyz.bomberman.game.data.LoginPlayerEvent.createLoginPlayerEvent = function(builder, idOffset, gameIdOffset) {
  xyz.bomberman.game.data.LoginPlayerEvent.startLoginPlayerEvent(builder);
  xyz.bomberman.game.data.LoginPlayerEvent.addId(builder, idOffset);
  xyz.bomberman.game.data.LoginPlayerEvent.addGameId(builder, gameIdOffset);
  return xyz.bomberman.game.data.LoginPlayerEvent.endLoginPlayerEvent(builder);
}

/**
 * @constructor
 */
xyz.bomberman.game.data.CreatePlayerEvent = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {xyz.bomberman.game.data.CreatePlayerEvent}
 */
xyz.bomberman.game.data.CreatePlayerEvent.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {xyz.bomberman.game.data.CreatePlayerEvent=} obj
 * @returns {xyz.bomberman.game.data.CreatePlayerEvent}
 */
xyz.bomberman.game.data.CreatePlayerEvent.getRootAsCreatePlayerEvent = function(bb, obj) {
  return (obj || new xyz.bomberman.game.data.CreatePlayerEvent).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {xyz.bomberman.game.data.CreatePlayerEvent=} obj
 * @returns {xyz.bomberman.game.data.CreatePlayerEvent}
 */
xyz.bomberman.game.data.CreatePlayerEvent.getSizePrefixedRootAsCreatePlayerEvent = function(bb, obj) {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new xyz.bomberman.game.data.CreatePlayerEvent).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
xyz.bomberman.game.data.CreatePlayerEvent.prototype.id = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @returns {number}
 */
xyz.bomberman.game.data.CreatePlayerEvent.prototype.x = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.readInt32(this.bb_pos + offset) : 0;
};

/**
 * @param {number} value
 * @returns {boolean}
 */
xyz.bomberman.game.data.CreatePlayerEvent.prototype.mutate_x = function(value) {
  var offset = this.bb.__offset(this.bb_pos, 6);

  if (offset === 0) {
    return false;
  }

  this.bb.writeInt32(this.bb_pos + offset, value);
  return true;
};

/**
 * @returns {number}
 */
xyz.bomberman.game.data.CreatePlayerEvent.prototype.y = function() {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? this.bb.readInt32(this.bb_pos + offset) : 0;
};

/**
 * @param {number} value
 * @returns {boolean}
 */
xyz.bomberman.game.data.CreatePlayerEvent.prototype.mutate_y = function(value) {
  var offset = this.bb.__offset(this.bb_pos, 8);

  if (offset === 0) {
    return false;
  }

  this.bb.writeInt32(this.bb_pos + offset, value);
  return true;
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
xyz.bomberman.game.data.CreatePlayerEvent.prototype.direction = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 10);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @returns {number}
 */
xyz.bomberman.game.data.CreatePlayerEvent.prototype.amountBombs = function() {
  var offset = this.bb.__offset(this.bb_pos, 12);
  return offset ? this.bb.readInt32(this.bb_pos + offset) : 0;
};

/**
 * @param {number} value
 * @returns {boolean}
 */
xyz.bomberman.game.data.CreatePlayerEvent.prototype.mutate_amountBombs = function(value) {
  var offset = this.bb.__offset(this.bb_pos, 12);

  if (offset === 0) {
    return false;
  }

  this.bb.writeInt32(this.bb_pos + offset, value);
  return true;
};

/**
 * @returns {number}
 */
xyz.bomberman.game.data.CreatePlayerEvent.prototype.amountWalls = function() {
  var offset = this.bb.__offset(this.bb_pos, 14);
  return offset ? this.bb.readInt32(this.bb_pos + offset) : 0;
};

/**
 * @param {number} value
 * @returns {boolean}
 */
xyz.bomberman.game.data.CreatePlayerEvent.prototype.mutate_amountWalls = function(value) {
  var offset = this.bb.__offset(this.bb_pos, 14);

  if (offset === 0) {
    return false;
  }

  this.bb.writeInt32(this.bb_pos + offset, value);
  return true;
};

/**
 * @returns {number}
 */
xyz.bomberman.game.data.CreatePlayerEvent.prototype.health = function() {
  var offset = this.bb.__offset(this.bb_pos, 16);
  return offset ? this.bb.readInt32(this.bb_pos + offset) : 0;
};

/**
 * @param {number} value
 * @returns {boolean}
 */
xyz.bomberman.game.data.CreatePlayerEvent.prototype.mutate_health = function(value) {
  var offset = this.bb.__offset(this.bb_pos, 16);

  if (offset === 0) {
    return false;
  }

  this.bb.writeInt32(this.bb_pos + offset, value);
  return true;
};

/**
 * @param {flatbuffers.Builder} builder
 */
xyz.bomberman.game.data.CreatePlayerEvent.startCreatePlayerEvent = function(builder) {
  builder.startObject(7);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} idOffset
 */
xyz.bomberman.game.data.CreatePlayerEvent.addId = function(builder, idOffset) {
  builder.addFieldOffset(0, idOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} x
 */
xyz.bomberman.game.data.CreatePlayerEvent.addX = function(builder, x) {
  builder.addFieldInt32(1, x, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} y
 */
xyz.bomberman.game.data.CreatePlayerEvent.addY = function(builder, y) {
  builder.addFieldInt32(2, y, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} directionOffset
 */
xyz.bomberman.game.data.CreatePlayerEvent.addDirection = function(builder, directionOffset) {
  builder.addFieldOffset(3, directionOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} amountBombs
 */
xyz.bomberman.game.data.CreatePlayerEvent.addAmountBombs = function(builder, amountBombs) {
  builder.addFieldInt32(4, amountBombs, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} amountWalls
 */
xyz.bomberman.game.data.CreatePlayerEvent.addAmountWalls = function(builder, amountWalls) {
  builder.addFieldInt32(5, amountWalls, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} health
 */
xyz.bomberman.game.data.CreatePlayerEvent.addHealth = function(builder, health) {
  builder.addFieldInt32(6, health, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
xyz.bomberman.game.data.CreatePlayerEvent.endCreatePlayerEvent = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} idOffset
 * @param {number} x
 * @param {number} y
 * @param {flatbuffers.Offset} directionOffset
 * @param {number} amountBombs
 * @param {number} amountWalls
 * @param {number} health
 * @returns {flatbuffers.Offset}
 */
xyz.bomberman.game.data.CreatePlayerEvent.createCreatePlayerEvent = function(builder, idOffset, x, y, directionOffset, amountBombs, amountWalls, health) {
  xyz.bomberman.game.data.CreatePlayerEvent.startCreatePlayerEvent(builder);
  xyz.bomberman.game.data.CreatePlayerEvent.addId(builder, idOffset);
  xyz.bomberman.game.data.CreatePlayerEvent.addX(builder, x);
  xyz.bomberman.game.data.CreatePlayerEvent.addY(builder, y);
  xyz.bomberman.game.data.CreatePlayerEvent.addDirection(builder, directionOffset);
  xyz.bomberman.game.data.CreatePlayerEvent.addAmountBombs(builder, amountBombs);
  xyz.bomberman.game.data.CreatePlayerEvent.addAmountWalls(builder, amountWalls);
  xyz.bomberman.game.data.CreatePlayerEvent.addHealth(builder, health);
  return xyz.bomberman.game.data.CreatePlayerEvent.endCreatePlayerEvent(builder);
}

/**
 * @constructor
 */
xyz.bomberman.game.data.CreateWallEvent = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {xyz.bomberman.game.data.CreateWallEvent}
 */
xyz.bomberman.game.data.CreateWallEvent.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {xyz.bomberman.game.data.CreateWallEvent=} obj
 * @returns {xyz.bomberman.game.data.CreateWallEvent}
 */
xyz.bomberman.game.data.CreateWallEvent.getRootAsCreateWallEvent = function(bb, obj) {
  return (obj || new xyz.bomberman.game.data.CreateWallEvent).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {xyz.bomberman.game.data.CreateWallEvent=} obj
 * @returns {xyz.bomberman.game.data.CreateWallEvent}
 */
xyz.bomberman.game.data.CreateWallEvent.getSizePrefixedRootAsCreateWallEvent = function(bb, obj) {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new xyz.bomberman.game.data.CreateWallEvent).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {number} index
 * @param {xyz.bomberman.game.data.Wall=} obj
 * @returns {xyz.bomberman.game.data.Wall}
 */
xyz.bomberman.game.data.CreateWallEvent.prototype.walls = function(index, obj) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? (obj || new xyz.bomberman.game.data.Wall).__init(this.bb.__indirect(this.bb.__vector(this.bb_pos + offset) + index * 4), this.bb) : null;
};

/**
 * @returns {number}
 */
xyz.bomberman.game.data.CreateWallEvent.prototype.wallsLength = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @param {flatbuffers.Builder} builder
 */
xyz.bomberman.game.data.CreateWallEvent.startCreateWallEvent = function(builder) {
  builder.startObject(1);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} wallsOffset
 */
xyz.bomberman.game.data.CreateWallEvent.addWalls = function(builder, wallsOffset) {
  builder.addFieldOffset(0, wallsOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {Array.<flatbuffers.Offset>} data
 * @returns {flatbuffers.Offset}
 */
xyz.bomberman.game.data.CreateWallEvent.createWallsVector = function(builder, data) {
  builder.startVector(4, data.length, 4);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]);
  }
  return builder.endVector();
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
xyz.bomberman.game.data.CreateWallEvent.startWallsVector = function(builder, numElems) {
  builder.startVector(4, numElems, 4);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
xyz.bomberman.game.data.CreateWallEvent.endCreateWallEvent = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} wallsOffset
 * @returns {flatbuffers.Offset}
 */
xyz.bomberman.game.data.CreateWallEvent.createCreateWallEvent = function(builder, wallsOffset) {
  xyz.bomberman.game.data.CreateWallEvent.startCreateWallEvent(builder);
  xyz.bomberman.game.data.CreateWallEvent.addWalls(builder, wallsOffset);
  return xyz.bomberman.game.data.CreateWallEvent.endCreateWallEvent(builder);
}

/**
 * @constructor
 */
xyz.bomberman.game.data.CreateItemEvent = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {xyz.bomberman.game.data.CreateItemEvent}
 */
xyz.bomberman.game.data.CreateItemEvent.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {xyz.bomberman.game.data.CreateItemEvent=} obj
 * @returns {xyz.bomberman.game.data.CreateItemEvent}
 */
xyz.bomberman.game.data.CreateItemEvent.getRootAsCreateItemEvent = function(bb, obj) {
  return (obj || new xyz.bomberman.game.data.CreateItemEvent).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {xyz.bomberman.game.data.CreateItemEvent=} obj
 * @returns {xyz.bomberman.game.data.CreateItemEvent}
 */
xyz.bomberman.game.data.CreateItemEvent.getSizePrefixedRootAsCreateItemEvent = function(bb, obj) {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new xyz.bomberman.game.data.CreateItemEvent).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {xyz.bomberman.game.data.Position=} obj
 * @returns {xyz.bomberman.game.data.Position|null}
 */
xyz.bomberman.game.data.CreateItemEvent.prototype.position = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? (obj || new xyz.bomberman.game.data.Position).__init(this.bb_pos + offset, this.bb) : null;
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
xyz.bomberman.game.data.CreateItemEvent.prototype.type = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
xyz.bomberman.game.data.CreateItemEvent.startCreateItemEvent = function(builder) {
  builder.startObject(2);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} positionOffset
 */
xyz.bomberman.game.data.CreateItemEvent.addPosition = function(builder, positionOffset) {
  builder.addFieldStruct(0, positionOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} typeOffset
 */
xyz.bomberman.game.data.CreateItemEvent.addType = function(builder, typeOffset) {
  builder.addFieldOffset(1, typeOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
xyz.bomberman.game.data.CreateItemEvent.endCreateItemEvent = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} positionOffset
 * @param {flatbuffers.Offset} typeOffset
 * @returns {flatbuffers.Offset}
 */
xyz.bomberman.game.data.CreateItemEvent.createCreateItemEvent = function(builder, positionOffset, typeOffset) {
  xyz.bomberman.game.data.CreateItemEvent.startCreateItemEvent(builder);
  xyz.bomberman.game.data.CreateItemEvent.addPosition(builder, positionOffset);
  xyz.bomberman.game.data.CreateItemEvent.addType(builder, typeOffset);
  return xyz.bomberman.game.data.CreateItemEvent.endCreateItemEvent(builder);
}

/**
 * @constructor
 */
xyz.bomberman.game.data.ChangeDirectionEvent = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {xyz.bomberman.game.data.ChangeDirectionEvent}
 */
xyz.bomberman.game.data.ChangeDirectionEvent.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {xyz.bomberman.game.data.ChangeDirectionEvent=} obj
 * @returns {xyz.bomberman.game.data.ChangeDirectionEvent}
 */
xyz.bomberman.game.data.ChangeDirectionEvent.getRootAsChangeDirectionEvent = function(bb, obj) {
  return (obj || new xyz.bomberman.game.data.ChangeDirectionEvent).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {xyz.bomberman.game.data.ChangeDirectionEvent=} obj
 * @returns {xyz.bomberman.game.data.ChangeDirectionEvent}
 */
xyz.bomberman.game.data.ChangeDirectionEvent.getSizePrefixedRootAsChangeDirectionEvent = function(bb, obj) {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new xyz.bomberman.game.data.ChangeDirectionEvent).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
xyz.bomberman.game.data.ChangeDirectionEvent.prototype.id = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
xyz.bomberman.game.data.ChangeDirectionEvent.prototype.direction = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
xyz.bomberman.game.data.ChangeDirectionEvent.startChangeDirectionEvent = function(builder) {
  builder.startObject(2);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} idOffset
 */
xyz.bomberman.game.data.ChangeDirectionEvent.addId = function(builder, idOffset) {
  builder.addFieldOffset(0, idOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} directionOffset
 */
xyz.bomberman.game.data.ChangeDirectionEvent.addDirection = function(builder, directionOffset) {
  builder.addFieldOffset(1, directionOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
xyz.bomberman.game.data.ChangeDirectionEvent.endChangeDirectionEvent = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} idOffset
 * @param {flatbuffers.Offset} directionOffset
 * @returns {flatbuffers.Offset}
 */
xyz.bomberman.game.data.ChangeDirectionEvent.createChangeDirectionEvent = function(builder, idOffset, directionOffset) {
  xyz.bomberman.game.data.ChangeDirectionEvent.startChangeDirectionEvent(builder);
  xyz.bomberman.game.data.ChangeDirectionEvent.addId(builder, idOffset);
  xyz.bomberman.game.data.ChangeDirectionEvent.addDirection(builder, directionOffset);
  return xyz.bomberman.game.data.ChangeDirectionEvent.endChangeDirectionEvent(builder);
}

/**
 * @constructor
 */
xyz.bomberman.game.data.GrabItemEvent = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {xyz.bomberman.game.data.GrabItemEvent}
 */
xyz.bomberman.game.data.GrabItemEvent.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {xyz.bomberman.game.data.GrabItemEvent=} obj
 * @returns {xyz.bomberman.game.data.GrabItemEvent}
 */
xyz.bomberman.game.data.GrabItemEvent.getRootAsGrabItemEvent = function(bb, obj) {
  return (obj || new xyz.bomberman.game.data.GrabItemEvent).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {xyz.bomberman.game.data.GrabItemEvent=} obj
 * @returns {xyz.bomberman.game.data.GrabItemEvent}
 */
xyz.bomberman.game.data.GrabItemEvent.getSizePrefixedRootAsGrabItemEvent = function(bb, obj) {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new xyz.bomberman.game.data.GrabItemEvent).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {xyz.bomberman.game.data.Item=} obj
 * @returns {xyz.bomberman.game.data.Item|null}
 */
xyz.bomberman.game.data.GrabItemEvent.prototype.item = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? (obj || new xyz.bomberman.game.data.Item).__init(this.bb.__indirect(this.bb_pos + offset), this.bb) : null;
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
xyz.bomberman.game.data.GrabItemEvent.prototype.playerId = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
xyz.bomberman.game.data.GrabItemEvent.startGrabItemEvent = function(builder) {
  builder.startObject(2);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} itemOffset
 */
xyz.bomberman.game.data.GrabItemEvent.addItem = function(builder, itemOffset) {
  builder.addFieldOffset(0, itemOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} playerIdOffset
 */
xyz.bomberman.game.data.GrabItemEvent.addPlayerId = function(builder, playerIdOffset) {
  builder.addFieldOffset(1, playerIdOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
xyz.bomberman.game.data.GrabItemEvent.endGrabItemEvent = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} itemOffset
 * @param {flatbuffers.Offset} playerIdOffset
 * @returns {flatbuffers.Offset}
 */
xyz.bomberman.game.data.GrabItemEvent.createGrabItemEvent = function(builder, itemOffset, playerIdOffset) {
  xyz.bomberman.game.data.GrabItemEvent.startGrabItemEvent(builder);
  xyz.bomberman.game.data.GrabItemEvent.addItem(builder, itemOffset);
  xyz.bomberman.game.data.GrabItemEvent.addPlayerId(builder, playerIdOffset);
  return xyz.bomberman.game.data.GrabItemEvent.endGrabItemEvent(builder);
}

/**
 * @constructor
 */
xyz.bomberman.game.data.HurtPlayerEvent = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {xyz.bomberman.game.data.HurtPlayerEvent}
 */
xyz.bomberman.game.data.HurtPlayerEvent.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {xyz.bomberman.game.data.HurtPlayerEvent=} obj
 * @returns {xyz.bomberman.game.data.HurtPlayerEvent}
 */
xyz.bomberman.game.data.HurtPlayerEvent.getRootAsHurtPlayerEvent = function(bb, obj) {
  return (obj || new xyz.bomberman.game.data.HurtPlayerEvent).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {xyz.bomberman.game.data.HurtPlayerEvent=} obj
 * @returns {xyz.bomberman.game.data.HurtPlayerEvent}
 */
xyz.bomberman.game.data.HurtPlayerEvent.getSizePrefixedRootAsHurtPlayerEvent = function(bb, obj) {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new xyz.bomberman.game.data.HurtPlayerEvent).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
xyz.bomberman.game.data.HurtPlayerEvent.prototype.id = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
xyz.bomberman.game.data.HurtPlayerEvent.startHurtPlayerEvent = function(builder) {
  builder.startObject(1);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} idOffset
 */
xyz.bomberman.game.data.HurtPlayerEvent.addId = function(builder, idOffset) {
  builder.addFieldOffset(0, idOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
xyz.bomberman.game.data.HurtPlayerEvent.endHurtPlayerEvent = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} idOffset
 * @returns {flatbuffers.Offset}
 */
xyz.bomberman.game.data.HurtPlayerEvent.createHurtPlayerEvent = function(builder, idOffset) {
  xyz.bomberman.game.data.HurtPlayerEvent.startHurtPlayerEvent(builder);
  xyz.bomberman.game.data.HurtPlayerEvent.addId(builder, idOffset);
  return xyz.bomberman.game.data.HurtPlayerEvent.endHurtPlayerEvent(builder);
}

/**
 * @constructor
 */
xyz.bomberman.game.data.MovePlayerEvent = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {xyz.bomberman.game.data.MovePlayerEvent}
 */
xyz.bomberman.game.data.MovePlayerEvent.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {xyz.bomberman.game.data.MovePlayerEvent=} obj
 * @returns {xyz.bomberman.game.data.MovePlayerEvent}
 */
xyz.bomberman.game.data.MovePlayerEvent.getRootAsMovePlayerEvent = function(bb, obj) {
  return (obj || new xyz.bomberman.game.data.MovePlayerEvent).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {xyz.bomberman.game.data.MovePlayerEvent=} obj
 * @returns {xyz.bomberman.game.data.MovePlayerEvent}
 */
xyz.bomberman.game.data.MovePlayerEvent.getSizePrefixedRootAsMovePlayerEvent = function(bb, obj) {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new xyz.bomberman.game.data.MovePlayerEvent).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
xyz.bomberman.game.data.MovePlayerEvent.prototype.id = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @returns {number}
 */
xyz.bomberman.game.data.MovePlayerEvent.prototype.x = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.readInt32(this.bb_pos + offset) : 0;
};

/**
 * @param {number} value
 * @returns {boolean}
 */
xyz.bomberman.game.data.MovePlayerEvent.prototype.mutate_x = function(value) {
  var offset = this.bb.__offset(this.bb_pos, 6);

  if (offset === 0) {
    return false;
  }

  this.bb.writeInt32(this.bb_pos + offset, value);
  return true;
};

/**
 * @returns {number}
 */
xyz.bomberman.game.data.MovePlayerEvent.prototype.y = function() {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? this.bb.readInt32(this.bb_pos + offset) : 0;
};

/**
 * @param {number} value
 * @returns {boolean}
 */
xyz.bomberman.game.data.MovePlayerEvent.prototype.mutate_y = function(value) {
  var offset = this.bb.__offset(this.bb_pos, 8);

  if (offset === 0) {
    return false;
  }

  this.bb.writeInt32(this.bb_pos + offset, value);
  return true;
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
xyz.bomberman.game.data.MovePlayerEvent.prototype.direction = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 10);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
xyz.bomberman.game.data.MovePlayerEvent.startMovePlayerEvent = function(builder) {
  builder.startObject(4);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} idOffset
 */
xyz.bomberman.game.data.MovePlayerEvent.addId = function(builder, idOffset) {
  builder.addFieldOffset(0, idOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} x
 */
xyz.bomberman.game.data.MovePlayerEvent.addX = function(builder, x) {
  builder.addFieldInt32(1, x, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} y
 */
xyz.bomberman.game.data.MovePlayerEvent.addY = function(builder, y) {
  builder.addFieldInt32(2, y, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} directionOffset
 */
xyz.bomberman.game.data.MovePlayerEvent.addDirection = function(builder, directionOffset) {
  builder.addFieldOffset(3, directionOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
xyz.bomberman.game.data.MovePlayerEvent.endMovePlayerEvent = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} idOffset
 * @param {number} x
 * @param {number} y
 * @param {flatbuffers.Offset} directionOffset
 * @returns {flatbuffers.Offset}
 */
xyz.bomberman.game.data.MovePlayerEvent.createMovePlayerEvent = function(builder, idOffset, x, y, directionOffset) {
  xyz.bomberman.game.data.MovePlayerEvent.startMovePlayerEvent(builder);
  xyz.bomberman.game.data.MovePlayerEvent.addId(builder, idOffset);
  xyz.bomberman.game.data.MovePlayerEvent.addX(builder, x);
  xyz.bomberman.game.data.MovePlayerEvent.addY(builder, y);
  xyz.bomberman.game.data.MovePlayerEvent.addDirection(builder, directionOffset);
  return xyz.bomberman.game.data.MovePlayerEvent.endMovePlayerEvent(builder);
}

/**
 * @constructor
 */
xyz.bomberman.game.data.PlaceBombEvent = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {xyz.bomberman.game.data.PlaceBombEvent}
 */
xyz.bomberman.game.data.PlaceBombEvent.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {xyz.bomberman.game.data.PlaceBombEvent=} obj
 * @returns {xyz.bomberman.game.data.PlaceBombEvent}
 */
xyz.bomberman.game.data.PlaceBombEvent.getRootAsPlaceBombEvent = function(bb, obj) {
  return (obj || new xyz.bomberman.game.data.PlaceBombEvent).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {xyz.bomberman.game.data.PlaceBombEvent=} obj
 * @returns {xyz.bomberman.game.data.PlaceBombEvent}
 */
xyz.bomberman.game.data.PlaceBombEvent.getSizePrefixedRootAsPlaceBombEvent = function(bb, obj) {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new xyz.bomberman.game.data.PlaceBombEvent).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
xyz.bomberman.game.data.PlaceBombEvent.prototype.id = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @returns {number}
 */
xyz.bomberman.game.data.PlaceBombEvent.prototype.x = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.readInt32(this.bb_pos + offset) : 0;
};

/**
 * @param {number} value
 * @returns {boolean}
 */
xyz.bomberman.game.data.PlaceBombEvent.prototype.mutate_x = function(value) {
  var offset = this.bb.__offset(this.bb_pos, 6);

  if (offset === 0) {
    return false;
  }

  this.bb.writeInt32(this.bb_pos + offset, value);
  return true;
};

/**
 * @returns {number}
 */
xyz.bomberman.game.data.PlaceBombEvent.prototype.y = function() {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? this.bb.readInt32(this.bb_pos + offset) : 0;
};

/**
 * @param {number} value
 * @returns {boolean}
 */
xyz.bomberman.game.data.PlaceBombEvent.prototype.mutate_y = function(value) {
  var offset = this.bb.__offset(this.bb_pos, 8);

  if (offset === 0) {
    return false;
  }

  this.bb.writeInt32(this.bb_pos + offset, value);
  return true;
};

/**
 * @returns {number}
 */
xyz.bomberman.game.data.PlaceBombEvent.prototype.amountBombs = function() {
  var offset = this.bb.__offset(this.bb_pos, 10);
  return offset ? this.bb.readInt32(this.bb_pos + offset) : 0;
};

/**
 * @param {number} value
 * @returns {boolean}
 */
xyz.bomberman.game.data.PlaceBombEvent.prototype.mutate_amountBombs = function(value) {
  var offset = this.bb.__offset(this.bb_pos, 10);

  if (offset === 0) {
    return false;
  }

  this.bb.writeInt32(this.bb_pos + offset, value);
  return true;
};

/**
 * @param {flatbuffers.Builder} builder
 */
xyz.bomberman.game.data.PlaceBombEvent.startPlaceBombEvent = function(builder) {
  builder.startObject(4);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} idOffset
 */
xyz.bomberman.game.data.PlaceBombEvent.addId = function(builder, idOffset) {
  builder.addFieldOffset(0, idOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} x
 */
xyz.bomberman.game.data.PlaceBombEvent.addX = function(builder, x) {
  builder.addFieldInt32(1, x, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} y
 */
xyz.bomberman.game.data.PlaceBombEvent.addY = function(builder, y) {
  builder.addFieldInt32(2, y, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} amountBombs
 */
xyz.bomberman.game.data.PlaceBombEvent.addAmountBombs = function(builder, amountBombs) {
  builder.addFieldInt32(3, amountBombs, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
xyz.bomberman.game.data.PlaceBombEvent.endPlaceBombEvent = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} idOffset
 * @param {number} x
 * @param {number} y
 * @param {number} amountBombs
 * @returns {flatbuffers.Offset}
 */
xyz.bomberman.game.data.PlaceBombEvent.createPlaceBombEvent = function(builder, idOffset, x, y, amountBombs) {
  xyz.bomberman.game.data.PlaceBombEvent.startPlaceBombEvent(builder);
  xyz.bomberman.game.data.PlaceBombEvent.addId(builder, idOffset);
  xyz.bomberman.game.data.PlaceBombEvent.addX(builder, x);
  xyz.bomberman.game.data.PlaceBombEvent.addY(builder, y);
  xyz.bomberman.game.data.PlaceBombEvent.addAmountBombs(builder, amountBombs);
  return xyz.bomberman.game.data.PlaceBombEvent.endPlaceBombEvent(builder);
}

/**
 * @constructor
 */
xyz.bomberman.game.data.UpdateInventoryEvent = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {xyz.bomberman.game.data.UpdateInventoryEvent}
 */
xyz.bomberman.game.data.UpdateInventoryEvent.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {xyz.bomberman.game.data.UpdateInventoryEvent=} obj
 * @returns {xyz.bomberman.game.data.UpdateInventoryEvent}
 */
xyz.bomberman.game.data.UpdateInventoryEvent.getRootAsUpdateInventoryEvent = function(bb, obj) {
  return (obj || new xyz.bomberman.game.data.UpdateInventoryEvent).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {xyz.bomberman.game.data.UpdateInventoryEvent=} obj
 * @returns {xyz.bomberman.game.data.UpdateInventoryEvent}
 */
xyz.bomberman.game.data.UpdateInventoryEvent.getSizePrefixedRootAsUpdateInventoryEvent = function(bb, obj) {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new xyz.bomberman.game.data.UpdateInventoryEvent).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
xyz.bomberman.game.data.UpdateInventoryEvent.prototype.id = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @returns {number}
 */
xyz.bomberman.game.data.UpdateInventoryEvent.prototype.amountWalls = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.readInt32(this.bb_pos + offset) : 0;
};

/**
 * @param {number} value
 * @returns {boolean}
 */
xyz.bomberman.game.data.UpdateInventoryEvent.prototype.mutate_amountWalls = function(value) {
  var offset = this.bb.__offset(this.bb_pos, 6);

  if (offset === 0) {
    return false;
  }

  this.bb.writeInt32(this.bb_pos + offset, value);
  return true;
};

/**
 * @returns {number}
 */
xyz.bomberman.game.data.UpdateInventoryEvent.prototype.amountBombs = function() {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? this.bb.readInt32(this.bb_pos + offset) : 0;
};

/**
 * @param {number} value
 * @returns {boolean}
 */
xyz.bomberman.game.data.UpdateInventoryEvent.prototype.mutate_amountBombs = function(value) {
  var offset = this.bb.__offset(this.bb_pos, 8);

  if (offset === 0) {
    return false;
  }

  this.bb.writeInt32(this.bb_pos + offset, value);
  return true;
};

/**
 * @returns {number}
 */
xyz.bomberman.game.data.UpdateInventoryEvent.prototype.health = function() {
  var offset = this.bb.__offset(this.bb_pos, 10);
  return offset ? this.bb.readInt32(this.bb_pos + offset) : 0;
};

/**
 * @param {number} value
 * @returns {boolean}
 */
xyz.bomberman.game.data.UpdateInventoryEvent.prototype.mutate_health = function(value) {
  var offset = this.bb.__offset(this.bb_pos, 10);

  if (offset === 0) {
    return false;
  }

  this.bb.writeInt32(this.bb_pos + offset, value);
  return true;
};

/**
 * @param {flatbuffers.Builder} builder
 */
xyz.bomberman.game.data.UpdateInventoryEvent.startUpdateInventoryEvent = function(builder) {
  builder.startObject(4);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} idOffset
 */
xyz.bomberman.game.data.UpdateInventoryEvent.addId = function(builder, idOffset) {
  builder.addFieldOffset(0, idOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} amountWalls
 */
xyz.bomberman.game.data.UpdateInventoryEvent.addAmountWalls = function(builder, amountWalls) {
  builder.addFieldInt32(1, amountWalls, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} amountBombs
 */
xyz.bomberman.game.data.UpdateInventoryEvent.addAmountBombs = function(builder, amountBombs) {
  builder.addFieldInt32(2, amountBombs, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} health
 */
xyz.bomberman.game.data.UpdateInventoryEvent.addHealth = function(builder, health) {
  builder.addFieldInt32(3, health, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
xyz.bomberman.game.data.UpdateInventoryEvent.endUpdateInventoryEvent = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} idOffset
 * @param {number} amountWalls
 * @param {number} amountBombs
 * @param {number} health
 * @returns {flatbuffers.Offset}
 */
xyz.bomberman.game.data.UpdateInventoryEvent.createUpdateInventoryEvent = function(builder, idOffset, amountWalls, amountBombs, health) {
  xyz.bomberman.game.data.UpdateInventoryEvent.startUpdateInventoryEvent(builder);
  xyz.bomberman.game.data.UpdateInventoryEvent.addId(builder, idOffset);
  xyz.bomberman.game.data.UpdateInventoryEvent.addAmountWalls(builder, amountWalls);
  xyz.bomberman.game.data.UpdateInventoryEvent.addAmountBombs(builder, amountBombs);
  xyz.bomberman.game.data.UpdateInventoryEvent.addHealth(builder, health);
  return xyz.bomberman.game.data.UpdateInventoryEvent.endUpdateInventoryEvent(builder);
}

/**
 * @constructor
 */
xyz.bomberman.game.data.PlaceWallEvent = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {xyz.bomberman.game.data.PlaceWallEvent}
 */
xyz.bomberman.game.data.PlaceWallEvent.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {xyz.bomberman.game.data.PlaceWallEvent=} obj
 * @returns {xyz.bomberman.game.data.PlaceWallEvent}
 */
xyz.bomberman.game.data.PlaceWallEvent.getRootAsPlaceWallEvent = function(bb, obj) {
  return (obj || new xyz.bomberman.game.data.PlaceWallEvent).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {xyz.bomberman.game.data.PlaceWallEvent=} obj
 * @returns {xyz.bomberman.game.data.PlaceWallEvent}
 */
xyz.bomberman.game.data.PlaceWallEvent.getSizePrefixedRootAsPlaceWallEvent = function(bb, obj) {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new xyz.bomberman.game.data.PlaceWallEvent).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
xyz.bomberman.game.data.PlaceWallEvent.prototype.id = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
xyz.bomberman.game.data.PlaceWallEvent.prototype.wallId = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @returns {number}
 */
xyz.bomberman.game.data.PlaceWallEvent.prototype.x = function() {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? this.bb.readInt32(this.bb_pos + offset) : 0;
};

/**
 * @param {number} value
 * @returns {boolean}
 */
xyz.bomberman.game.data.PlaceWallEvent.prototype.mutate_x = function(value) {
  var offset = this.bb.__offset(this.bb_pos, 8);

  if (offset === 0) {
    return false;
  }

  this.bb.writeInt32(this.bb_pos + offset, value);
  return true;
};

/**
 * @returns {number}
 */
xyz.bomberman.game.data.PlaceWallEvent.prototype.y = function() {
  var offset = this.bb.__offset(this.bb_pos, 10);
  return offset ? this.bb.readInt32(this.bb_pos + offset) : 0;
};

/**
 * @param {number} value
 * @returns {boolean}
 */
xyz.bomberman.game.data.PlaceWallEvent.prototype.mutate_y = function(value) {
  var offset = this.bb.__offset(this.bb_pos, 10);

  if (offset === 0) {
    return false;
  }

  this.bb.writeInt32(this.bb_pos + offset, value);
  return true;
};

/**
 * @returns {number}
 */
xyz.bomberman.game.data.PlaceWallEvent.prototype.amountWalls = function() {
  var offset = this.bb.__offset(this.bb_pos, 12);
  return offset ? this.bb.readInt32(this.bb_pos + offset) : 0;
};

/**
 * @param {number} value
 * @returns {boolean}
 */
xyz.bomberman.game.data.PlaceWallEvent.prototype.mutate_amountWalls = function(value) {
  var offset = this.bb.__offset(this.bb_pos, 12);

  if (offset === 0) {
    return false;
  }

  this.bb.writeInt32(this.bb_pos + offset, value);
  return true;
};

/**
 * @param {flatbuffers.Builder} builder
 */
xyz.bomberman.game.data.PlaceWallEvent.startPlaceWallEvent = function(builder) {
  builder.startObject(5);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} idOffset
 */
xyz.bomberman.game.data.PlaceWallEvent.addId = function(builder, idOffset) {
  builder.addFieldOffset(0, idOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} wallIdOffset
 */
xyz.bomberman.game.data.PlaceWallEvent.addWallId = function(builder, wallIdOffset) {
  builder.addFieldOffset(1, wallIdOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} x
 */
xyz.bomberman.game.data.PlaceWallEvent.addX = function(builder, x) {
  builder.addFieldInt32(2, x, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} y
 */
xyz.bomberman.game.data.PlaceWallEvent.addY = function(builder, y) {
  builder.addFieldInt32(3, y, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} amountWalls
 */
xyz.bomberman.game.data.PlaceWallEvent.addAmountWalls = function(builder, amountWalls) {
  builder.addFieldInt32(4, amountWalls, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
xyz.bomberman.game.data.PlaceWallEvent.endPlaceWallEvent = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} idOffset
 * @param {flatbuffers.Offset} wallIdOffset
 * @param {number} x
 * @param {number} y
 * @param {number} amountWalls
 * @returns {flatbuffers.Offset}
 */
xyz.bomberman.game.data.PlaceWallEvent.createPlaceWallEvent = function(builder, idOffset, wallIdOffset, x, y, amountWalls) {
  xyz.bomberman.game.data.PlaceWallEvent.startPlaceWallEvent(builder);
  xyz.bomberman.game.data.PlaceWallEvent.addId(builder, idOffset);
  xyz.bomberman.game.data.PlaceWallEvent.addWallId(builder, wallIdOffset);
  xyz.bomberman.game.data.PlaceWallEvent.addX(builder, x);
  xyz.bomberman.game.data.PlaceWallEvent.addY(builder, y);
  xyz.bomberman.game.data.PlaceWallEvent.addAmountWalls(builder, amountWalls);
  return xyz.bomberman.game.data.PlaceWallEvent.endPlaceWallEvent(builder);
}

/**
 * @constructor
 */
xyz.bomberman.game.data.ReactionEvent = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {xyz.bomberman.game.data.ReactionEvent}
 */
xyz.bomberman.game.data.ReactionEvent.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {xyz.bomberman.game.data.ReactionEvent=} obj
 * @returns {xyz.bomberman.game.data.ReactionEvent}
 */
xyz.bomberman.game.data.ReactionEvent.getRootAsReactionEvent = function(bb, obj) {
  return (obj || new xyz.bomberman.game.data.ReactionEvent).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {xyz.bomberman.game.data.ReactionEvent=} obj
 * @returns {xyz.bomberman.game.data.ReactionEvent}
 */
xyz.bomberman.game.data.ReactionEvent.getSizePrefixedRootAsReactionEvent = function(bb, obj) {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new xyz.bomberman.game.data.ReactionEvent).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
xyz.bomberman.game.data.ReactionEvent.prototype.id = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
xyz.bomberman.game.data.ReactionEvent.prototype.reaction = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
xyz.bomberman.game.data.ReactionEvent.startReactionEvent = function(builder) {
  builder.startObject(2);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} idOffset
 */
xyz.bomberman.game.data.ReactionEvent.addId = function(builder, idOffset) {
  builder.addFieldOffset(0, idOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} reactionOffset
 */
xyz.bomberman.game.data.ReactionEvent.addReaction = function(builder, reactionOffset) {
  builder.addFieldOffset(1, reactionOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
xyz.bomberman.game.data.ReactionEvent.endReactionEvent = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} idOffset
 * @param {flatbuffers.Offset} reactionOffset
 * @returns {flatbuffers.Offset}
 */
xyz.bomberman.game.data.ReactionEvent.createReactionEvent = function(builder, idOffset, reactionOffset) {
  xyz.bomberman.game.data.ReactionEvent.startReactionEvent(builder);
  xyz.bomberman.game.data.ReactionEvent.addId(builder, idOffset);
  xyz.bomberman.game.data.ReactionEvent.addReaction(builder, reactionOffset);
  return xyz.bomberman.game.data.ReactionEvent.endReactionEvent(builder);
}

/**
 * @constructor
 */
xyz.bomberman.game.data.DeletePlayerEvent = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {xyz.bomberman.game.data.DeletePlayerEvent}
 */
xyz.bomberman.game.data.DeletePlayerEvent.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {xyz.bomberman.game.data.DeletePlayerEvent=} obj
 * @returns {xyz.bomberman.game.data.DeletePlayerEvent}
 */
xyz.bomberman.game.data.DeletePlayerEvent.getRootAsDeletePlayerEvent = function(bb, obj) {
  return (obj || new xyz.bomberman.game.data.DeletePlayerEvent).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {xyz.bomberman.game.data.DeletePlayerEvent=} obj
 * @returns {xyz.bomberman.game.data.DeletePlayerEvent}
 */
xyz.bomberman.game.data.DeletePlayerEvent.getSizePrefixedRootAsDeletePlayerEvent = function(bb, obj) {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new xyz.bomberman.game.data.DeletePlayerEvent).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
xyz.bomberman.game.data.DeletePlayerEvent.prototype.id = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
xyz.bomberman.game.data.DeletePlayerEvent.startDeletePlayerEvent = function(builder) {
  builder.startObject(1);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} idOffset
 */
xyz.bomberman.game.data.DeletePlayerEvent.addId = function(builder, idOffset) {
  builder.addFieldOffset(0, idOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
xyz.bomberman.game.data.DeletePlayerEvent.endDeletePlayerEvent = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} idOffset
 * @returns {flatbuffers.Offset}
 */
xyz.bomberman.game.data.DeletePlayerEvent.createDeletePlayerEvent = function(builder, idOffset) {
  xyz.bomberman.game.data.DeletePlayerEvent.startDeletePlayerEvent(builder);
  xyz.bomberman.game.data.DeletePlayerEvent.addId(builder, idOffset);
  return xyz.bomberman.game.data.DeletePlayerEvent.endDeletePlayerEvent(builder);
}

/**
 * @constructor
 */
xyz.bomberman.game.data.GameEvent = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {xyz.bomberman.game.data.GameEvent}
 */
xyz.bomberman.game.data.GameEvent.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {xyz.bomberman.game.data.GameEvent=} obj
 * @returns {xyz.bomberman.game.data.GameEvent}
 */
xyz.bomberman.game.data.GameEvent.getRootAsGameEvent = function(bb, obj) {
  return (obj || new xyz.bomberman.game.data.GameEvent).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {xyz.bomberman.game.data.GameEvent=} obj
 * @returns {xyz.bomberman.game.data.GameEvent}
 */
xyz.bomberman.game.data.GameEvent.getSizePrefixedRootAsGameEvent = function(bb, obj) {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new xyz.bomberman.game.data.GameEvent).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {xyz.bomberman.game.data.EventType}
 */
xyz.bomberman.game.data.GameEvent.prototype.eventType = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? /** @type {xyz.bomberman.game.data.EventType} */ (this.bb.readUint8(this.bb_pos + offset)) : xyz.bomberman.game.data.EventType.NONE;
};

/**
 * @param {flatbuffers.Table} obj
 * @returns {?flatbuffers.Table}
 */
xyz.bomberman.game.data.GameEvent.prototype.event = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.__union(obj, this.bb_pos + offset) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
xyz.bomberman.game.data.GameEvent.startGameEvent = function(builder) {
  builder.startObject(2);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {xyz.bomberman.game.data.EventType} eventType
 */
xyz.bomberman.game.data.GameEvent.addEventType = function(builder, eventType) {
  builder.addFieldInt8(0, eventType, xyz.bomberman.game.data.EventType.NONE);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} eventOffset
 */
xyz.bomberman.game.data.GameEvent.addEvent = function(builder, eventOffset) {
  builder.addFieldOffset(1, eventOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
xyz.bomberman.game.data.GameEvent.endGameEvent = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} offset
 */
xyz.bomberman.game.data.GameEvent.finishGameEventBuffer = function(builder, offset) {
  builder.finish(offset);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} offset
 */
xyz.bomberman.game.data.GameEvent.finishSizePrefixedGameEventBuffer = function(builder, offset) {
  builder.finish(offset, undefined, true);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {xyz.bomberman.game.data.EventType} eventType
 * @param {flatbuffers.Offset} eventOffset
 * @returns {flatbuffers.Offset}
 */
xyz.bomberman.game.data.GameEvent.createGameEvent = function(builder, eventType, eventOffset) {
  xyz.bomberman.game.data.GameEvent.startGameEvent(builder);
  xyz.bomberman.game.data.GameEvent.addEventType(builder, eventType);
  xyz.bomberman.game.data.GameEvent.addEvent(builder, eventOffset);
  return xyz.bomberman.game.data.GameEvent.endGameEvent(builder);
}

// Exports for ECMAScript6 Modules
export {xyz};
