version: '2.1'

services:
  prometheus:
    image: prom/prometheus:v2.25.2
    build:
      network: host
    container_name: prometheus
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090

  grafana:
    build:
      network: host
    image: grafana/grafana:7.4.5
    container_name: grafana
    volumes:
      - ./datasources:/etc/grafana/provisioning/datasources
    ports:
      - 3000:3000
