global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'prometheus'

    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'local-rsocket-proxy-connected'

    scrape_interval: 10s
    scrape_timeout: 9s
    metrics_path: '/metrics/connected'
    static_configs:
      - targets: ['prometheus-rsocket-proxy:8080']

  - job_name: 'local-rsocket-proxy'

    scrape_interval: 10s
    scrape_timeout: 2s
    metrics_path: '/metrics/proxy'
    static_configs:
      - targets: ['prometheus-rsocket-proxy:8080']

rule_files:
  - prometheus_rules.yml